name: hydra
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - matplotlib=3.5.1
  - numpy=1.21.2
  - pandas=1.3.4
  - pip=21.2.4
  - python=3.9.12
  - pytorch=1.10.2
  - torchvision=0.11.3
  - pip:
    - hydra-core==1.1.1
    - omegaconf==2.1.1
    - pytorch-lightning==1.6.0
    - rich==12.2.0
    - tensorboard==2.8.0
    - tqdm==4.64.0
    - setuptools==59.5.0
    - protobuf==3.20.0